Repository DeveloperAcademy-POSTECH/2025-C4-M9-NoMyeolmang, pull requests merged in 2025-07, with the labels that each got.

#16 ⚙️ Setting: #14 MacOS 전면 개편에 따른 프로젝트 초기세팅
  NoMyeolmang/.swiftlint.yml
  NoMyeolmang/NoMyeolmang-iOS/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  NoMyeolmang/NoMyeolmang-iOS/Sources/App/AppRoute.swift
  NoMyeolmang/NoMyeolmang-iOS/Sources/App/AppRouter.swift
  NoMyeolmang/NoMyeolmang-iOS/Sources/App/RootView.swift
  NoMyeolmang/NoMyeolmang-iOS/Sources/Presentations/Home/HomeView.swift
  NoMyeolmang/NoMyeolmang-iOS/Sources/Presentations/Home/HomeViewModel.swift
  NoMyeolmang/NoMyeolmang-watch/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  NoMyeolmang/NoMyeolmang-watch/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  NoMyeolmang/NoMyeolmang-watch/Resources/Assets.xcassets/Contents.json
  NoMyeolmang/NoMyeolmang-watch/Sources/App/NoMyeolmangWatchApp.swift
  NoMyeolmang/NoMyeolmang-watch/Sources/Presentations/Home/HomeView.swift
  NoMyeolmang/NoMyeolmang-watch/Sources/Presentations/Home/HomeViewModel.swift
  NoMyeolmang/NoMyeolmang.xcodeproj/project.pbxproj
  NoMyeolmang/NoMyeolmang/NoMyeolmang.entitlements
  NoMyeolmang/NoMyeolmang/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  NoMyeolmang/NoMyeolmang/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  NoMyeolmang/NoMyeolmang/Resources/Assets.xcassets/Contents.json
  NoMyeolmang/NoMyeolmang/Sources/App/NoMyeolmangApp.swift
  NoMyeolmang/NoMyeolmang/Sources/Presentation/ContentView.swift
  NoMyeolmang/Shared/ML/ML.md
  NoMyeolmang/Shared/Models/Profile.swift
  NoMyeolmang/Shared/Services/TimeService.swift
Labels: ⚙️ Setting

#36 ✨ Feat: #35 네비게이션 코디네이터 #35
  NoMyeolmang/NoMyeolmang.xcodeproj/project.pbxproj
  NoMyeolmang/NoMyeolmang/Sources/App/AppCoordinator.swift
  NoMyeolmang/NoMyeolmang/Sources/App/AppRoute.swift
  NoMyeolmang/NoMyeolmang/Sources/App/NoMyeolmangApp.swift
  NoMyeolmang/NoMyeolmang/Sources/App/RootView.swift
  NoMyeolmang/NoMyeolmang/Sources/Presentation/FeedbackView.swift
  NoMyeolmang/NoMyeolmang/Sources/Presentation/ReportView.swift
  NoMyeolmang/NoMyeolmang/Sources/Presentation/TimerSettingView.swift
  NoMyeolmang/NoMyeolmang/Sources/Presentation/TimerView.swift
Labels: ✨ Feat

#50 ✨ Feat: #44 feedbackview
  NoMyeolmang/NoMyeolmang/Resources/Assets.xcassets/1C1C1ED9.colorset/Contents.json
  NoMyeolmang/NoMyeolmang/Resources/Assets.xcassets/5C436D.colorset/Contents.json
  NoMyeolmang/NoMyeolmang/Resources/Assets.xcassets/backgroundSpace.imageset/Contents.json
  NoMyeolmang/NoMyeolmang/Resources/Assets.xcassets/backgroundSpace.imageset/background 1.png
  NoMyeolmang/NoMyeolmang/Resources/Assets.xcassets/backgroundSpace.imageset/background 2.png
  NoMyeolmang/NoMyeolmang/Resources/Assets.xcassets/backgroundSpace.imageset/background.png
  NoMyeolmang/NoMyeolmang/Resources/Assets.xcassets/planet.imageset/Contents.json
  NoMyeolmang/NoMyeolmang/Resources/Assets.xcassets/planet.imageset/planet 1.png
  NoMyeolmang/NoMyeolmang/Resources/Assets.xcassets/planet.imageset/planet 2.png
  NoMyeolmang/NoMyeolmang/Resources/Assets.xcassets/planet.imageset/planet.png
  NoMyeolmang/NoMyeolmang/Sources/DesignSystem/BlurView.swift
  NoMyeolmang/NoMyeolmang/Sources/DesignSystem/GSButton.swift
  NoMyeolmang/NoMyeolmang/Sources/DesignSystem/GSFont.swift
  NoMyeolmang/NoMyeolmang/Sources/DesignSystem/TextStyleModifier.swift
  NoMyeolmang/NoMyeolmang/Sources/Presentation/FeedbackView.swift
  NoMyeolmang/NoMyeolmang/Sources/Presentation/FeedbackView/FeedbackView.swift
  NoMyeolmang/NoMyeolmang/Sources/Presentation/FeedbackView/HoverRatingView.swift
  NoMyeolmang/NoMyeolmang/Sources/Presentation/ReportView.swift
Labels: ✨ Feat

#72 ✨ Feat: #64 자체 블러 구현 한계로 Xcode 내 블러 이용
  NoMyeolmang/NoMyeolmang.xcodeproj/project.pbxproj
  NoMyeolmang/NoMyeolmang/Resources/Assets.xcassets/backgroundSpace.imageset/Contents.json
  NoMyeolmang/NoMyeolmang/Resources/Assets.xcassets/backgroundSpace.imageset/background 1.png
  NoMyeolmang/NoMyeolmang/Resources/Assets.xcassets/backgroundSpace.imageset/background 2.png
  NoMyeolmang/NoMyeolmang/Resources/Assets.xcassets/backgroundSpace.imageset/background.png
  NoMyeolmang/NoMyeolmang/Resources/Assets.xcassets/backgroundSpace.imageset/backgroundSpace 1.png
  NoMyeolmang/NoMyeolmang/Resources/Assets.xcassets/backgroundSpace.imageset/backgroundSpace 2.png
  NoMyeolmang/NoMyeolmang/Resources/Assets.xcassets/backgroundSpace.imageset/backgroundSpace.png
  NoMyeolmang/NoMyeolmang/Sources/DesignSystem/CustomBlurView.swift
  NoMyeolmang/NoMyeolmang/Sources/DesignSystem/GSButton.swift
  NoMyeolmang/NoMyeolmang/Sources/DesignSystem/ToggleTabView.swift
  NoMyeolmang/NoMyeolmang/Sources/ML/Services/FocusPersonalizater.swift
  NoMyeolmang/NoMyeolmang/Sources/Presentation/FeedbackView/FeedbackView.swift
  NoMyeolmang/NoMyeolmang/Sources/Presentation/TimerSettingView.swift
Labels: ✨ Feat

#85 ✨ Feat: #83 AnalysisManager 피처 생성 메서드 반환 형태 변경, 일부 코드 개선
  NoMyeolmang/NoMyeolmang/Sources/Manager/AnalysisManager.swift
Labels: ✨ Feat

#87 ✨ Feat: #75 상단바 아이콘
  NoMyeolmang/NoMyeolmang.xcodeproj/project.pbxproj
  NoMyeolmang/NoMyeolmang/Sources/App/NoMyeolmangApp.swift
  NoMyeolmang/NoMyeolmang/Sources/Presentation/Icon/AppDelegate.swift
  NoMyeolmang/NoMyeolmang/Sources/Presentation/Icon/PopoverView.swift
Labels: ✨ Feat

#88 Fix: #76 actualTimer에 종료 콜백함수 추가
  NoMyeolmang/NoMyeolmang/Sources/Service/ActualTimerManager.swift
  NoMyeolmang/NoMyeolmang/Sources/Service/VirtualTimerManager.swift
Labels: ❌ Delete, ✨ Feat

#90 Refactor: #89 TimerLeftStopView 분리 및 백그라운드 애니메이션 속도 조정
  NoMyeolmang/NoMyeolmang.xcodeproj/project.pbxproj
  NoMyeolmang/NoMyeolmang/Sources/ML/Models/FocusLevel.swift
  NoMyeolmang/NoMyeolmang/Sources/Presentation/TimerView/TimeLeftStopView.swift
  NoMyeolmang/NoMyeolmang/Sources/Presentation/TimerView/View/SpaceshipView.swift
  NoMyeolmang/NoMyeolmang/Sources/Presentation/TimerView/View/TimeLeftView.swift
  NoMyeolmang/NoMyeolmang/Sources/Presentation/TimerView/View/TimerBackgroundView.swift
  NoMyeolmang/NoMyeolmang/Sources/Presentation/TimerView/View/TimerStopButton.swift
  NoMyeolmang/NoMyeolmang/Sources/Presentation/TimerView/View/TimerView.swift
Labels: ❌ Delete, ✨ Feat, ♻️ Refactor

#94 ✨ Feat: #62 OnboardingView
  NoMyeolmang/NoMyeolmang.xcodeproj/project.pbxproj
  NoMyeolmang/NoMyeolmang/Resources/Assets.xcassets/191735.colorset/Contents.json
  NoMyeolmang/NoMyeolmang/Resources/Assets.xcassets/1F2687.colorset/Contents.json
  NoMyeolmang/NoMyeolmang/Resources/Assets.xcassets/232323.colorset/Contents.json
  NoMyeolmang/NoMyeolmang/Resources/Assets.xcassets/252525.colorset/Contents.json
  NoMyeolmang/NoMyeolmang/Resources/Assets.xcassets/7243D4.colorset/Contents.json
  NoMyeolmang/NoMyeolmang/Resources/Assets.xcassets/ButtonBackground.imageset/ButtonBackground.png
  NoMyeolmang/NoMyeolmang/Resources/Assets.xcassets/tooltipBubble1.imageset/Contents.json
  NoMyeolmang/NoMyeolmang/Resources/Assets.xcassets/tooltipBubble1.imageset/tooltipBubble1 1.png
  NoMyeolmang/NoMyeolmang/Resources/Assets.xcassets/tooltipBubble1.imageset/tooltipBubble1 2.png
  NoMyeolmang/NoMyeolmang/Resources/Assets.xcassets/tooltipBubble1.imageset/tooltipBubble1.png
  NoMyeolmang/NoMyeolmang/Resources/Assets.xcassets/tooltipBubble2.imageset/Contents.json
  NoMyeolmang/NoMyeolmang/Resources/Assets.xcassets/tooltipBubble2.imageset/tooltipBubble2 1.png
  NoMyeolmang/NoMyeolmang/Resources/Assets.xcassets/tooltipBubble2.imageset/tooltipBubble2 2.png
  NoMyeolmang/NoMyeolmang/Resources/Assets.xcassets/tooltipBubble2.imageset/tooltipBubble2.png
  NoMyeolmang/NoMyeolmang/Sources/App/RootView.swift
  NoMyeolmang/NoMyeolmang/Sources/DesignSystem/GSFont.swift
  NoMyeolmang/NoMyeolmang/Sources/Presentation/Onboarding/GuidanceTooltipView.swift
  NoMyeolmang/NoMyeolmang/Sources/Presentation/Onboarding/OnboardingContainerView.swift
  NoMyeolmang/NoMyeolmang/Sources/Presentation/Onboarding/OnboardingMainContentView.swift
  NoMyeolmang/NoMyeolmang/Sources/Presentation/Onboarding/OnboardingPopupOverlay.swift
  NoMyeolmang/NoMyeolmang/Sources/Presentation/Onboarding/OnboardingView.swift
  NoMyeolmang/NoMyeolmang/Sources/Presentation/Onboarding/PopupView.swift
  NoMyeolmang/NoMyeolmang/Sources/Presentation/TimerSettingView.swift
  NoMyeolmang/NoMyeolmang/Sources/Presentation/TimerSettingView/FocusTimeSetting.swift
  NoMyeolmang/NoMyeolmang/Sources/Presentation/TimerSettingView/NextButtonView.swift
  NoMyeolmang/NoMyeolmang/Sources/Presentation/TimerSettingView/PersonalTimerSettingView.swift
  NoMyeolmang/NoMyeolmang/Sources/Presentation/TimerSettingView/TimerSettingView.swift
  NoMyeolmang/NoMyeolmang/Sources/Presentation/TimerSettingView/ToggleTabView.swift
Labels: ✨ Feat

#107 Refactor: #102 RootView 개선
  NoMyeolmang/NoMyeolmang/Sources/App/RootView.swift
Labels: ♻️ Refactor

#97 Feat: #71 리포트뷰 UI 구현
  NoMyeolmang/NoMyeolmang/Sources/Presentation/ReportView/ReportView.swift
  NoMyeolmang/NoMyeolmang/Sources/Presentation/ReportView/TimerReportBox.swift
Labels: ✨ Feat, 🪽 Angie

#111 Feat: #67 TimerSetiingViewModel 구현 및 연결작업
  NoMyeolmang/NoMyeolmang.xcodeproj/project.pbxproj
  NoMyeolmang/NoMyeolmang/Sources/Presentation/Onboarding/OnboardingMainContentView.swift
  NoMyeolmang/NoMyeolmang/Sources/Presentation/TimerSettingView/View/FocusTimeSetting.swift
  NoMyeolmang/NoMyeolmang/Sources/Presentation/TimerSettingView/View/NextButtonView.swift
  NoMyeolmang/NoMyeolmang/Sources/Presentation/TimerSettingView/View/PersonalTimerSettingView.swift
  NoMyeolmang/NoMyeolmang/Sources/Presentation/TimerSettingView/View/TimerSettingView.swift
  NoMyeolmang/NoMyeolmang/Sources/Presentation/TimerSettingView/View/ToggleTabView.swift
  NoMyeolmang/NoMyeolmang/Sources/Presentation/TimerSettingView/ViewModel/TimerSettingViewModel.swift
Labels: ✨ Feat

#117 Refactor: #114 RootView N번째 개선 작업
  NoMyeolmang/NoMyeolmang/Sources/App/RootView.swift
Labels: ♻️ Refactor

#116 Refactor: #115 ReportView 배경 반응형 수정
  NoMyeolmang/NoMyeolmang/Sources/Presentation/ReportView/ReportView.swift
  NoMyeolmang/NoMyeolmang/Sources/Presentation/ReportView/ReportViewModel.swift
Labels: ♻️ Refactor

#120 Feat: #100 NumberTextField
  NoMyeolmang/NoMyeolmang.xcodeproj/project.pbxproj
  NoMyeolmang/NoMyeolmang/Sources/Presentation/TimerSettingView/View/PersonalTimerSettingView.swift
  NoMyeolmang/NoMyeolmang/Sources/Presentation/TimerSettingView/View/TimerSettingView.swift
  NoMyeolmang/NoMyeolmang/Sources/Presentation/TimerSettingView/View/ToggleTabView.swift
Labels: ✨ Feat

#130 Refactor: #126 앱 이름 변경
  NoMyeolmang/timé.xcodeproj/project.pbxproj
  NoMyeolmang/timé.xcodeproj/project.xcworkspace/contents.xcworkspacedata
Labels: ♻️ Refactor

#132 Fix: #131 상단바 메뉴 아이콘 복구 + 텍스트 입력 가능하도록 수정
  NoMyeolmang/NoMyeolmang.xcodeproj/xcshareddata/xcschemes/NoMyeolmang.xcscheme
  NoMyeolmang/NoMyeolmang/Sources/App/NoMyeolmangApp.swift
  NoMyeolmang/NoMyeolmang/Sources/Presentation/Popover/PopoverWindowController.swift
Labels: 🐞 Bug

#139 Fix: #136 팝오버 피드백뷰 호버 버튼 크기 수정
  NoMyeolmang/NoMyeolmang/Sources/Presentation/Popover/PopoverFeedback/PopoverRatingButton.swift
  NoMyeolmang/timé.xcodeproj/project.pbxproj
Labels: 🐞 Bug, 🎸 Gabi

#145 Fix: #135 타이머 세팅 뷰 수정사항 반영
  NoMyeolmang/NoMyeolmang/Sources/Presentation/TimerSettingView/View/PersonalTimerSettingView.swift
  NoMyeolmang/NoMyeolmang/Sources/Presentation/TimerSettingView/View/TimerSettingView.swift
  NoMyeolmang/NoMyeolmang/Sources/Presentation/TimerSettingView/View/ToggleTabView.swift
  NoMyeolmang/NoMyeolmang/Sources/Presentation/TimerSettingView/ViewModel/TimerSettingViewModel.swift
Labels: 🐞 Bug

#146 Fix: #140 타이머뷰 UI 개선 및 애니메이션 적용
  NoMyeolmang/NoMyeolmang/Resources/Assets.xcassets/spaceship.imageset/Contents.json
  NoMyeolmang/NoMyeolmang/Resources/Assets.xcassets/spaceship.imageset/Group 31.svg
  NoMyeolmang/NoMyeolmang/Resources/Assets.xcassets/spaceship.imageset/spaceship.svg
  NoMyeolmang/NoMyeolmang/Sources/Presentation/TimerView/View/TimeLeftView.swift
  NoMyeolmang/NoMyeolmang/Sources/Presentation/TimerView/View/TimerView.swift
  NoMyeolmang/NoMyeolmang/Sources/Presentation/TimerView/ViewModel/TimerViewModel.swift
  NoMyeolmang/timé.xcodeproj/project.pbxproj
Labels: 🐞 Bug, 🎸 Gabi

#148 Fix: #134 온보딩 뷰 수정
  NoMyeolmang/NoMyeolmang/Sources/Presentation/Onboarding/OnboardingMainContentView.swift
Labels: 🐞 Bug
